overrides:
  vite: npm:rolldown-vite@latest
catalog:
  '@antfu/eslint-config': 4.16.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/ri': ^1.2.5
  '@nuxt/eslint': 1.4.1
  '@nuxt/fonts': 0.11.4
  '@nuxt/icon': 1.14.0
  '@nuxt/image': 1.10.0
  '@nuxt/scripts': 0.11.8
  '@nuxt/test-utils': 3.19.1
  '@nuxtjs/color-mode': 3.5.2
  '@nuxtjs/i18n': 9.5.6
  '@nuxtjs/robots': 5.2.11
  '@nuxtjs/sitemap': 7.4.2
  '@tailwindcss/vite': ^4.1.11
  '@unhead/vue': ^2.0.11
  '@vueuse/core': ^13.4.0
  '@vueuse/nuxt': ^13.4.0
  eslint: ^9.30.0
  eslint-plugin-oxlint: ^1.4.0
  husky: ^9.1.7
  lint-staged: ^16.1.2
  nuxt: ^3.17.5
  oxlint: ^1.4.0
  tailwindcss: ^4.1.11
  vue: ^3.5.17
  vue-router: ^4.5.1

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
